#specifyFileName('01')

#Camera
setTrigger(2)  # The same as setTrigger('External "Start-trigger"')
setRecordMode(4)

#Lasers
setDigitalModulation('ON')
setDigitalPower('READOUT',50)
setLaser('488','ON')
setDigitalPower('OFF',100)
setLaser('488(2)','ON')
setDigitalPower('ON',25)
setLaser('405','ON')

#Scan
loadScan('scans/rs2_prConf')

for i in range(15):
	startRecord()
	startScan()
	waitUntilScanStop()
	setProgress((i+1)/15*100)
	stopRecord()
